#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : django-nose
Version  : 1.4.1
Release  : 12
URL      : https://pypi.python.org/packages/source/d/django-nose/django-nose-1.4.1.tar.gz
Source0  : https://pypi.python.org/packages/source/d/django-nose/django-nose-1.4.1.tar.gz
Summary  : Makes your Django tests simple and snappy
Group    : Development/Tools
License  : BSD-3-Clause
Requires: django-nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===========
django-nose
===========
.. image:: https://travis-ci.org/django-nose/django-nose.png
:target: https://travis-ci.org/django-nose/django-nose

%package python
Summary: python components for the django-nose package.
Group: Default

%description python
python components for the django-nose package.


%prep
%setup -q -n django-nose-1.4.1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
